### ISSUE TITLE
not recieving back from llama.cpp

### ISSUE THREAD

**Issue by zooteld** [3x3cut0r/llama-cpp-python-streamlit#1]
![2023-11-03_130748](https://github.com/3x3cut0r/llama-cpp-python-streamlit/assets/22121839/8a99b7e8-138a-4d01-bc4c-ce7cfb71bc72)

It appears its not receiving the response back from the llama.cpp server. please advise

**Comment by zooteld** [comment]
*I tested with the index.html that is included with llama.cpp and everything works as expected.

**Comment by 3x3cut0r** [comment]
Hi,
first of all, this app is far away of been used in production and still under development.

I tryed it with my own [llama-cpp-python docker container](https://hub.docker.com/r/3x3cut0r/llama-cpp-python) and it is working fine.

did you put your llama-api address into src/config.json?
did you test your api using postman or something else to check if it is running fine?
for example can you reach `http://<your-api-ip>:<port>/docs` ?

br

**Comment by zooteld** [comment]
Let me be clear that I am not complaining, but asking for help.

did you put your llama-api address into src/config.json? 
did you test your api using postman or something else to check if it is running fine?
for example can you reach http://<your-api-ip>:<port>/docs ?

Yes, yes, and no... I am using a local hosted llama.cpp server with amd cards I tested the server with the index.html that comes with it in its examples and it is working nicely but when i try to use this beautiful app i can see it hitting the server in the server console but its not assigned a task like the ones from the index.html.

to me it looks like the request might not be the correct format.

**Comment by 3x3cut0r** [comment]
Ok i got it.
It is because you are not using llama-cpp-python, but llama.cpp.
the projects have different endponts, see [here](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md).
i have not implemented the `/completion` endpoint yet and this is the only endpoint that is the same in both projects.
if i have time, i will implement switching endpoints soon.
currently it is set to `/v1/chat/completion`

**Comment by zooteld** [comment]
yes sir, I changed the /v1/chat/compleations to just compleation. 
it is connecting but after that it looses me

**Comment by zooteld** [comment]
my repo synced lol and now im getting a "no context to append"

**Comment by 3x3cut0r** [comment]
the problem is the other endpoint uses differend (json-)structure. by just switching the endpoint address it will not gonna work.

**Comment by zooteld** [comment]
ok thank you for this information. I will attempt to reasearch further into changing the endpoint json format, and maybe i will stumble across something. sorry if I bother you.

**Comment by 3x3cut0r** [comment]
I updated the app and added a endpoint dropdown to select other endpoints.
Try using `/completions` to use llama.cpp endpoint.
tell me if its working or if there are some bugs.

**Comment by zooteld** [comment]
That's awesome! yes I got it to connect and work. I had to use the api_like_OAI.py on the server and /v1/completions in the app. nice app!
